package com.nwq.code.liferecord.data_base.automatic;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nwq.code.liferecord.data_base.bean.fulcrum.FulcrumFactor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FULCRUM_FACTOR".
*/
public class FulcrumFactorDao extends AbstractDao<FulcrumFactor, Long> {

    public static final String TABLENAME = "FULCRUM_FACTOR";

    /**
     * Properties of entity FulcrumFactor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Text = new Property(1, String.class, "text", false, "TEXT");
        public final static Property Position = new Property(2, int.class, "position", false, "POSITION");
    }


    public FulcrumFactorDao(DaoConfig config) {
        super(config);
    }
    
    public FulcrumFactorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FULCRUM_FACTOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"TEXT\" TEXT NOT NULL ," + // 1: text
                "\"POSITION\" INTEGER NOT NULL );"); // 2: position
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FULCRUM_FACTOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FulcrumFactor entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getText());
        stmt.bindLong(3, entity.getPosition());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FulcrumFactor entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getText());
        stmt.bindLong(3, entity.getPosition());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public FulcrumFactor readEntity(Cursor cursor, int offset) {
        FulcrumFactor entity = new FulcrumFactor( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // text
            cursor.getInt(offset + 2) // position
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FulcrumFactor entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setText(cursor.getString(offset + 1));
        entity.setPosition(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FulcrumFactor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FulcrumFactor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FulcrumFactor entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
