package com.nwq.code.liferecord.data_base.automatic;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nwq.code.liferecord.data_base.bean.fulcrum.FulcrumType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FULCRUM_TYPE".
*/
public class FulcrumTypeDao extends AbstractDao<FulcrumType, Long> {

    public static final String TABLENAME = "FULCRUM_TYPE";

    /**
     * Properties of entity FulcrumType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ItemId = new Property(1, long.class, "ItemId", false, "ITEM_ID");
        public final static Property ParentId = new Property(2, long.class, "parentId", false, "PARENT_ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
    }


    public FulcrumTypeDao(DaoConfig config) {
        super(config);
    }
    
    public FulcrumTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FULCRUM_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"ITEM_ID\" INTEGER NOT NULL ," + // 1: ItemId
                "\"PARENT_ID\" INTEGER NOT NULL ," + // 2: parentId
                "\"NAME\" TEXT NOT NULL );"); // 3: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FULCRUM_TYPE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FulcrumType entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getItemId());
        stmt.bindLong(3, entity.getParentId());
        stmt.bindString(4, entity.getName());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FulcrumType entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getItemId());
        stmt.bindLong(3, entity.getParentId());
        stmt.bindString(4, entity.getName());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public FulcrumType readEntity(Cursor cursor, int offset) {
        FulcrumType entity = new FulcrumType( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // ItemId
            cursor.getLong(offset + 2), // parentId
            cursor.getString(offset + 3) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FulcrumType entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setItemId(cursor.getLong(offset + 1));
        entity.setParentId(cursor.getLong(offset + 2));
        entity.setName(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FulcrumType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FulcrumType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FulcrumType entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
